# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [8]:
# import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
# print(np.__version__)
# print(np.show_config())

#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
# np.zeros(10)
# # np.empty(2)

#### 4. How to find the memory size of any array (★☆☆)

In [11]:
# x = np.array([1, 2, 3])
# print("size:", x.size * x.itemsize)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
# import numpy
# numpy.info(numpy.add)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
# array = np.zeros(10)
# array[4] = 1
# print(array)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
# array = np.arange(10,49)
# print(array)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
# array = np.arange(1,10)
# rev = array[::-1]
# print(array)
# print(rev)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
# # matrix = np.matrix('0 1 2; 3 4 5;6 7 8')
# # print(matrix)
# array = np.arange(0, 9).reshape(3, 3)
# print(array)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
# # nz = np.nonzero([1,2,0,0,4,0])
# # print(nz)

# arr = np.array([1, 2, 0, 0, 4, 0])
# result = np.where((arr != 0))
# print(result)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
# matr = np.eye(3)
# print(matr)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [19]:
# cube = np.random.rand(3,3,3)
# print (cube)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
import numpy as np

nz = np.random.randint(0,100,(10,10))
print(nz)
print(nz.max())
print(nz.min())

[[33  9  2 57 99 43 87 65 54 50]
 [59 34 95 42 18 46 34 19 32  4]
 [ 5 41 55 77 77 28 84 29 83 66]
 [51 67 33 21 59 71 34 71  5 40]
 [32 52  3  3 57 80 61 23 31 89]
 [71 58 14 79 10 74 39 93 85 85]
 [90 46 40 30 74 25  9  2 24 93]
 [83 82 33 74 42 64 20 39 87 63]
 [65 29 58 80 44 22 78 41 36 49]
 [50 29 90 25 35 59 86  4 11 16]]
99
2


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr = np.random.randint(0,100,(1,30))
print(np.mean(arr))

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr2d = np.random.randint(0,100,(10,10))
arr2d.fill(1)
arr2d[1:-1, 1:-1] = 0
print(arr2d)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arr2d = np.ones((3,3))
arr2d = np.pad(arr2d, pad_width = 1, mode = 'constant', constant_values = 0)
print(arr2d)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
1. 0      #nan        1
2. true   #False      0
3. false  #False      1
4. 0      #nan        1
5. true   #True       1
6. true   #False      0

3.0

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix, [0,1,2,3,4] )
print (matrix)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
np.unravel_index(100,(6,7,8))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
arr = np.array([[0, 1], [1, 0]])
print(np.tile(arr, (4,4)))

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
x= np.random.random((5,5))
xmax = x.max()
xmin = x.min()
print(x)
x = (x - xmin)/(xmax - xmin)
print(x)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
x = np.random.random((5,3))
y = np.random.random((3,2))
z = np.dot(x, y)
print(x, y, z)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array = np.arange(20)
array[(array > 3) & (array < 8)] = -1
print(array)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
[-2.14748365e+09]

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.array([32.11, 51.5, 0.112])
print(np.round(Z,0))

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array1 = [10, 20, 50]
array2 = [10, 30, 40]
print(np.intersect1d(array1, array2))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all="ignore")
array = np.arange(10) / 0

print(array)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Today: ",today,"\nYestraday: ",yesterday ,"\nTomorrow: ",tomorrow)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (Z.astype(int))
print (np.trunc(Z))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
x = np.zeros((5,5))
x += np.arange(5)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def get_generator():
   for n in range(10):
       yield n
print(np.fromiter(get_generator(),dtype=int,count=-1))


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.linspace(0, 1, num=12)[1:-1]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array = np.random.random(10)
x.sort()

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arry = np.array([1, 2, 3, 4])
sum = np.add.reduce(arry)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
arry1 = np.random.randint(0,2,6)
arry2 = np.random.randint(0,2,6)
print(np.allclose(x, y))

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
z= np.random.random((10,2))
x = z[:,0]
y = z[:,1]
print(np.sqrt(x**2+y**2))
print(np.arctan2(y,x))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
arry = np.arange(10)
arry[arry.argmax()] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
🤷‍♂️
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
C = 1.0 / np.subtract.outer(X, Y)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.random.random(40)
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
array = np.arange(100)
random_number = np.random.uniform(0,100)
print(random_number)
index = (np.abs(array-random_number)).argmin()
print(array[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
matrix = np.zeros(4,[('position',    
                [ ('x', float, 1),('y', float, 1)]),
                ('color',
                [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(matrix)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
array = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
distance = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(distance)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
fll = (np.random.rand(10)*100).astype(np.float32)
inn = fll.view(np.int32)
inn[:] = fll
print(inn)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
matrix = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
matrix = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(matrix):
    print(index, value)
for index in np.ndindex(matrix.shape):
    print(index, matrix[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,2,4), np.linspace(-1,2,4))
d = np.sqrt(x*x+y*y)
sigma = 1.0
mu = 0.0
Un_G = np.exp(-( (d - mu)**2 / ( 2.0 * sigma**2 ) ) )
print(Un_G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
matrix = np.zeros((n,n))
np.put(matrix, np.random.choice(range(n*n), p, replace=False),1)
print(matrix)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
matrix = np.random.rand(5, 10)
print(matrix.mean(axis=1).reshape(-1, 1))

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
matrix = np.random.randint(0,10,(3,3))
print(matrix)
print(matrix[matrix[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
matrix = np.random.randint(0,3,(3,10))
print((~matrix.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
matrix = np.random.uniform(0,1,10)
print(matrix)
error = 0.5
print(matrix.flat[np.abs(matrix - error).argmin()])
***

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n = len(np.unique(I24))
print(n)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
Z0 = np.zeros(len(Z) + (len(Z)-1)*(3))
Z0[::4] = Z
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)